In [1]:
import glob
import os
import pandas as pd

In [2]:
# Caminhos padrões para os arquivos e pastas
caminho_raw = "../dados/raw/"
arquivos_bacen_resumo = "../dados/bacen/resumo_bacen/resumo_*.csv"
arquivos_bacen_dre = "../dados/bacen/dre_bacen/dre_*.csv"

lista_arquivo_resumo = glob.glob(arquivos_bacen_resumo)
lista_arquivo_dre = glob.glob(arquivos_bacen_dre)

Importação para o RESUMO (IF.DATA BACEN)

In [3]:
# Compilação dos diversos arquivos de RESUMO que foi importado do banco central
lista_resumo = []

for arquivo_resumo in lista_arquivo_resumo:
    temp_df_resumo = pd.read_csv(arquivo_resumo, sep=";", encoding='utf-8', low_memory=False)
    lista_resumo.append(temp_df_resumo)

df_resumo_total = pd.concat(lista_resumo, ignore_index=True)

df_resumo_total.columns = df_resumo_total.columns.str.strip()

In [4]:
# Equalização das colunas, pois ao longo dos anos foram feitas mudanças nos nomes.
df_resumo = df_resumo_total.copy()

df_resumo['Carteira de Crédito'] = df_resumo['Carteira de Crédito'].fillna(df_resumo['Carteira de Crédito Classificada'])
df_resumo['Passivo Exigível'] = df_resumo['Passivo Exigível'].fillna(df_resumo['Passivo Circulante e Exigível a Longo Prazo e Resultados de Exercícios Futuros'])

# Limpeza de colunas vazias, por conta de 'colunas_titulo'. Além de limpeza de linhas em vazio, que apontavam linhas de legenda, e as utilizadas para equalizar as novas.
colunas_excluir = ['Carteira de Crédito Classificada','Conglomerado Prudencial.1', 'Passivo Circulante e Exigível a Longo Prazo e Resultados de Exercícios Futuros', 'Títulos e Valores Mobiliários', 'Conglomerado Financeiro']

colunas_vazias = [c for c in df_resumo.columns if c.startswith('Unnamed')]

colunas_para_excluir = colunas_excluir + colunas_vazias

df_resumo = df_resumo.drop(columns=colunas_para_excluir)
df_resumo = df_resumo.dropna(subset='Cidade')

# Salvar o dataframe bruto na pasta 'RAW'.
df_resumo.to_parquet(os.path.join(caminho_raw, "resumo_raw.parquet"), index=False)

df_resumo.info()
df_resumo

<class 'pandas.core.frame.DataFrame'>
Index: 17170 entries, 0 to 17939
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Instituição                      17170 non-null  object
 1   Código                           17170 non-null  float64
 2   Conglomerado Prudencial          8373 non-null   object
 3   TCB                              17170 non-null  object
 4   TC                               17170 non-null  float64
 5   TI                               17170 non-null  float64
 6   Cidade                           17170 non-null  object
 7   UF                               17170 non-null  object
 8   Data                             17170 non-null  object
 9   Ativo Total                      17170 non-null  object
 10  Captações                        17170 non-null  object
 11  Patrimônio Líquido               17170 non-null  object
 12  Lucro Líquido                    17170 non-null  object
 13  Número de Agências               17170 non-null  object
 14  Número de Postos de Atendimento  17170 non-null  object
 15  Carteira de Crédito              17170 non-null  object
 16  Passivo Exigível                 17170 non-null  object
dtypes: float64(3), object(14)
memory usage: 2.4+ MB

,Instituição,Código,Conglomerado Prudencial,TCB,TC,TI,Cidade,UF,Data,Ativo Total,Captações,Patrimônio Líquido,Lucro Líquido,Número de Agências,Número de Postos de Atendimento,Carteira de Crédito,Passivo Exigível
0,BANCO DO BRASIL S.A.,0.0,BB - PRUDENCIAL,b1,1.0,1.0,BRASILIA,DF,12/2022,1.927.604.248,1.551.106.608,153.546.924,16.638.371,3.985,604,853.636.272,1.774.057.324
1,ITAÚ UNIBANCO S.A.,60701190.0,ITAU - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,12/2022,1.621.520.167,1.323.163.687,129.564.325,15.943.927,2.584,1.003,406.186.786,1.491.955.842
2,CAIXA ECONOMICA FEDERAL,360305.0,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1.0,6.0,BRASILIA,DF,12/2022,1.585.795.602,1.315.128.052,84.813.538,5.493.435,3.373,937,1.012.344.567,1.500.982.064
3,BANCO BRADESCO S.A.,60746948.0,BRADESCO - PRUDENCIAL,b1,2.0,8.0,OSASCO,SP,12/2022,1.489.174.462,1.147.488.387,154.263.223,6.647.656,2.865,1.277,543.700.762,1.334.911.238
4,BANCO SANTANDER (BRASIL) S.A.,90400888.0,SANTANDER - PRUDENCIAL,b1,3.0,8.0,SAO PAULO,SP,12/2022,986.299.576,722.481.108,81.076.905,4.582.139,2.573,1.557,341.933.356,905.222.672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17935,CREDI-SHOP - SOCIEDADE DE CRÉDITO DIRETO S.A.,54733010.0,CREDI SHOP S.A. - PRUDENCIAL,n1,2.0,43.0,TERESINA,PI,06/2025,NI,NI,NI,NI,2,0,NI,NI
17936,PERSONAL SOCIEDADE DE CRÉDITO DIRETO S.A.,57905133.0,PERSONAL SCD - PRUDENCIAL,n1,2.0,43.0,FLORIANOPOLIS,SC,06/2025,NI,NI,NI,NI,2,0,NI,NI
17937,BANCO PINE S.A.,62144175.0,PINE - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,06/2025,NI,NI,NI,NI,3,0,NI,NI
17938,BT CORRETORA DE CÂMBIO LTDA.,73622748.0,BT CC - PRUDENCIAL,n2,2.0,21.0,SAO PAULO,SP,06/2025,NI,NI,NI,NI,4,0,NI,NI
17939,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS TR...,90560434.0,NaN,b3S,2.0,9.0,CACHOEIRINHA,RS,06/2025,NI,NI,NI,NI,0,0,NI,NI

Importação para o DRE (IF.DATA BACEN)

In [5]:
# Compilação dos diversos arquivos de DRE que foi importado do banco central

lista_dre = []

for arquivo_dre in lista_arquivo_dre:
    temp_df_dre = pd.read_csv(arquivo_dre, sep=";", encoding='utf-8', low_memory=False)
    lista_dre.append(temp_df_dre)

df_dre_total = pd.concat(lista_dre, ignore_index=True)

df_dre_total.columns = df_dre_total.columns.str.strip()

In [6]:
df_dre = df_dre_total.copy()

# Equalização das colunas, pois ao longo dos anos foram feitas mudanças nos nomes.
df_dre['Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)'] = df_dre['Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)'].fillna(df_dre['Resultado antes da Tributação, Lucro e Participação (g) = (e) + (f)'])
df_dre['Lucro Líquido (aa) = (x) + (y) + (z)'] = df_dre['Lucro Líquido (aa) = (x) + (y) + (z)'].fillna(df_dre['Lucro Líquido (j) = (g) + (h) + (i)'])
df_dre['Outras Receitas / Despesas'] = df_dre['Outras Receitas / Despesas'].fillna(df_dre['Outras Receitas/Despesas Operacionais'])
df_dre['Participações no Lucro (z)'] = df_dre['Participações no Lucro (z)'].fillna(df_dre['Participação nos Lucros (i)'])
df_dre['Imposto de Renda e Contribuição Social (y)'] = df_dre['Imposto de Renda e Contribuição Social (y)'].fillna(df_dre['Imposto de Renda e Contribuição Social (h)'])
df_dre['Resultado com Transações de Pagamento'] = df_dre['Resultado com Transações de Pagamento'].fillna('0')

# Limpeza de colunas vazias, por conta de 'colunas_titulo'. Além de limpeza de linhas em vazio, que apontavam linhas de legenda, e as utilizadas para equalizar as novas.
colunas_vazias = [c for c in df_dre.columns if c.startswith('Unnamed')]
colunas_excluir = ['Conglomerado Financeiro', 'Conglomerado Prudencial.1', 'Ativo Total', 'Resultado antes da Tributação, Lucro e Participação (g) = (e) + (f)','Lucro Líquido (j) = (g) + (h) + (i)','Outras Receitas/Despesas Operacionais','Imposto de Renda e Contribuição Social (h)','Participação nos Lucros (i)','Juros Sobre Capital Social de Cooperativas (k)','Resultado Operacional (e) = (c) + (d)','Resultado Não Operacional (f)']

colunas_exclusão = colunas_vazias + colunas_excluir

df_dre = df_dre.dropna(subset='Cidade')
df_dre = df_dre.drop(columns=colunas_exclusão)

# Salvar o dataframe bruto na pasta 'RAW'.
df_dre.to_parquet(os.path.join(caminho_raw, "dre_raw.parquet"), index=False)

df_dre.info()
df_dre

<class 'pandas.core.frame.DataFrame'>
Index: 17170 entries, 2 to 17961
Data columns (total 16 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Instituição                                                          17170 non-null  object
 1   Código                                                               17170 non-null  float64
 2   Conglomerado Prudencial                                              8373 non-null   object
 3   TCB                                                                  17170 non-null  object
 4   TC                                                                   17170 non-null  float64
 5   TI                                                                   17170 non-null  float64
 6   Cidade                                                               17170 non-null  object
 7   UF                                                                   17170 non-null  object
 8   Data                                                                 17170 non-null  object
 9   Resultado de Intermediação Financeira                                17170 non-null  object
 10  Resultado com Transações de Pagamento                                17170 non-null  object
 11  Outras Receitas / Despesas                                           17170 non-null  object
 12  Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)  17170 non-null  object
 13  Imposto de Renda e Contribuição Social (y)                           17170 non-null  object
 14  Participações no Lucro (z)                                           17170 non-null  object
 15  Lucro Líquido (aa) = (x) + (y) + (z)                                 17170 non-null  object
dtypes: float64(3), object(13)
memory usage: 2.2+ MB

,Instituição,Código,Conglomerado Prudencial,TCB,TC,TI,Cidade,UF,Data,Resultado de Intermediação Financeira,Resultado com Transações de Pagamento,Outras Receitas / Despesas,Resultado antes da Tributação e Participações (x) = (k) + (l) + (w),Imposto de Renda e Contribuição Social (y),Participações no Lucro (z),Lucro Líquido (aa) = (x) + (y) + (z)
2,BANCO DO BRASIL S.A.,0.0,BB - PRUDENCIAL,b1,1.0,1.0,BRASILIA,DF,12/2022,58.297.195,0,6.287.062,21.753.526,-2.982.566,-2.132.589,16.638.371
3,CAIXA ECONOMICA FEDERAL,360305.0,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1.0,6.0,BRASILIA,DF,12/2022,56.235.680,0,8.480.850,5.582.178,971.396,-1.060.139,5.493.435
4,ITAÚ UNIBANCO S.A.,60701190.0,ITAU - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,12/2022,36.162.795,0,4.631.069,18.299.359,1.334.900,-3.690.333,15.943.927
5,BANCO BRADESCO S.A.,60746948.0,BRADESCO - PRUDENCIAL,b1,2.0,8.0,OSASCO,SP,12/2022,44.706.379,0,6.034.638,2.897.870,3.749.785,0,6.647.656
6,BANCO SANTANDER (BRASIL) S.A.,90400888.0,SANTANDER - PRUDENCIAL,b1,3.0,8.0,SAO PAULO,SP,12/2022,26.385.861,0,5.637.941,2.602.071,2.970.185,-990.117,4.582.139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17957,CREDI-SHOP - SOCIEDADE DE CRÉDITO DIRETO S.A.,54733010.0,CREDI SHOP S.A. - PRUDENCIAL,n1,2.0,43.0,TERESINA,PI,06/2025,NI,NI,NI,NI,NI,NI,NI
17958,PERSONAL SOCIEDADE DE CRÉDITO DIRETO S.A.,57905133.0,PERSONAL SCD - PRUDENCIAL,n1,2.0,43.0,FLORIANOPOLIS,SC,06/2025,NI,NI,NI,NI,NI,NI,NI
17959,BANCO PINE S.A.,62144175.0,PINE - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,06/2025,NI,NI,NI,NI,NI,NI,NI
17960,BT CORRETORA DE CÂMBIO LTDA.,73622748.0,BT CC - PRUDENCIAL,n2,2.0,21.0,SAO PAULO,SP,06/2025,NI,NI,NI,NI,NI,NI,NI
17961,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS TR...,90560434.0,NaN,b3S,2.0,9.0,CACHOEIRINHA,RS,06/2025,NI,NI,NI,NI,NI,NI,NI