In [90]:
import glob
import os
import pandas as pd

In [91]:
# Caminhos padrões para os arquivos e pastas
caminho_raw = "../dados/raw/"
arquivos_bacen_resumo = "../dados/bacen/resumo_bacen/resumo_*.csv"
arquivos_bacen_dre = "../dados/bacen/dre_bacen/dre_*.csv"

lista_arquivo_resumo = glob.glob(arquivos_bacen_resumo)

Importação para o RESUMO (IF.DATA BACEN)

In [92]:
# Compilação dos diversos arquivos de RESUMO que foi importado do banco central
lista_resumo = []

for arquivo_resumo in lista_arquivo_resumo:
    temp_df_resumo = pd.read_csv(arquivo_resumo, sep=";", encoding='utf-8', low_memory=False)
    lista_resumo.append(temp_df_resumo)

df_resumo_total = pd.concat(lista_resumo, ignore_index=True)

df_resumo_total.columns = df_resumo_total.columns.str.strip()

In [93]:
# Equalização das colunas, pois ao longo dos anos foram feitas mudanças nos nomes.
df_resumo = df_resumo_total.copy()

df_resumo['Carteira de Crédito'] = df_resumo['Carteira de Crédito'].fillna(df_resumo['Carteira de Crédito Classificada'])
df_resumo['Passivo Exigível'] = df_resumo['Passivo Exigível'].fillna(df_resumo['Passivo Circulante e Exigível a Longo Prazo e Resultados de Exercícios Futuros'])

# Limpeza de colunas vazias, por conta de 'colunas_titulo'. Além de limpeza de linhas em vazio, que apontavam linhas de legenda, e as utilizadas para equalizar as novas.
colunas_excluir = ['Carteira de Crédito Classificada','Conglomerado Prudencial.1', 'Passivo Circulante e Exigível a Longo Prazo e Resultados de Exercícios Futuros', 'Títulos e Valores Mobiliários', 'Conglomerado Financeiro']

colunas_vazias = [c for c in df_resumo.columns if c.startswith('Unnamed')]

colunas_para_excluir = colunas_excluir + colunas_vazias

df_resumo = df_resumo.drop(columns=colunas_para_excluir)
df_resumo = df_resumo.dropna(subset='Cidade')

# Salvar o dataframe bruto na pasta 'RAW'.
df_resumo.to_parquet(os.path.join(caminho_raw, "resumo_raw.parquet"), index=False)

df_resumo.info()
df_resumo.head()

<class 'pandas.core.frame.DataFrame'>
Index: 17170 entries, 0 to 17939
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Instituição                      17170 non-null  object
 1   Código                           17170 non-null  float64
 2   Conglomerado Prudencial          8373 non-null   object
 3   TCB                              17170 non-null  object
 4   TC                               17170 non-null  float64
 5   TI                               17170 non-null  float64
 6   Cidade                           17170 non-null  object
 7   UF                               17170 non-null  object
 8   Data                             17170 non-null  object
 9   Ativo Total                      17170 non-null  object
 10  Captações                        17170 non-null  object
 11  Patrimônio Líquido               17170 non-null  object
 12  Lucro Líquido                    17170 non-null  object
 13  Número de Agências               17170 non-null  object
 14  Número de Postos de Atendimento  17170 non-null  object
 15  Carteira de Crédito              17170 non-null  object
 16  Passivo Exigível                 17170 non-null  object
dtypes: float64(3), object(14)
memory usage: 2.4+ MB

,Instituição,Código,Conglomerado Prudencial,TCB,TC,TI,Cidade,UF,Data,Ativo Total,Captações,Patrimônio Líquido,Lucro Líquido,Número de Agências,Número de Postos de Atendimento,Carteira de Crédito,Passivo Exigível
0,BANCO DO BRASIL S.A.,0.0,BB - PRUDENCIAL,b1,1.0,1.0,BRASILIA,DF,12/2022,1.927.604.248,1.551.106.608,153.546.924,16.638.371,3.985,604,853.636.272,1.774.057.324
1,ITAÚ UNIBANCO S.A.,60701190.0,ITAU - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,12/2022,1.621.520.167,1.323.163.687,129.564.325,15.943.927,2.584,1.003,406.186.786,1.491.955.842
2,CAIXA ECONOMICA FEDERAL,360305.0,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1.0,6.0,BRASILIA,DF,12/2022,1.585.795.602,1.315.128.052,84.813.538,5.493.435,3.373,937,1.012.344.567,1.500.982.064
3,BANCO BRADESCO S.A.,60746948.0,BRADESCO - PRUDENCIAL,b1,2.0,8.0,OSASCO,SP,12/2022,1.489.174.462,1.147.488.387,154.263.223,6.647.656,2.865,1.277,543.700.762,1.334.911.238
4,BANCO SANTANDER (BRASIL) S.A.,90400888.0,SANTANDER - PRUDENCIAL,b1,3.0,8.0,SAO PAULO,SP,12/2022,986.299.576,722.481.108,81.076.905,4.582.139,2.573,1.557,341.933.356,905.222.672

Importação para o DRE (IF.DATA BACEN)

In [94]:
import pandas as pd
import glob

# Compilação dos diversos arquivos de DRE
lista_dre = []
lista_arquivo_dre = glob.glob(arquivos_bacen_dre)

for arquivo_dre in lista_arquivo_dre:
    temp_df_dre = pd.read_csv(
        arquivo_dre, sep=";",
        encoding='utf-8',
        header=[0, 1, 2],
        on_bad_lines='skip'
    )

    # --- INÍCIO DA LIMPEZA DOS CABEÇALHOS ---
    novas_colunas = []

    for coluna in temp_df_dre.columns:
        # 1. Filtra 'Unnamed'
        partes_validas = [str(x) for x in coluna if "Unnamed" not in str(x)]
        
        # 2. Pega o último nome válido
        if partes_validas:
            nome_final = partes_validas[-1].strip()
        else:
            nome_final = "Coluna_Vazia"
            
        novas_colunas.append(nome_final)

    # --- NOVO PASSO: DEDUPLICAÇÃO ---
    # Se houver nomes repetidos na lista 'novas_colunas', adiciona um sufixo (_1, _2, etc)
    colunas_unicas = []
    contador_nomes = {}

    for nome in novas_colunas:
        if nome in contador_nomes:
            contador_nomes[nome] += 1
            # Cria nome novo: Ex: "Data_1", "Valor_2"
            novo_nome = f"{nome}_{contador_nomes[nome]}"
        else:
            contador_nomes[nome] = 0
            novo_nome = nome
            
        colunas_unicas.append(novo_nome)
    
    # Aplica os nomes JÁ DEDUPLICADOS ao DataFrame
    temp_df_dre.columns = colunas_unicas
    # --------------------------------

    lista_dre.append(temp_df_dre)

# --- FIM DA LIMPEZA E CONCATENAÇÃO ---

# Agora o concat funcionará porque não existem colunas ambíguas dentro dos arquivos
df_dre_total = pd.concat(lista_dre, ignore_index=True)

df_dre_total.info()
df_dre_total

C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(
C:\Users\Thiag\AppData\Local\Temp\ipykernel_15752\2901768193.py:9: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  temp_df_dre = pd.read_csv(

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17203 entries, 0 to 17202
Data columns (total 94 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   Instituição                                                                                            17203 non-null  object
 1   Código                                                                                                 17170 non-null  float64
 2   Conglomerado Prudencial                                                                                8373 non-null   object
 3   Conglomerado Financeiro                                                                                2600 non-null   float64
 4   Conglomerado Prudencial_1                                                                              8374 non-null   float64
 5   TCB                                                                                                    17170 non-null  object
 6   TC                                                                                                     17170 non-null  float64
 7   TI                                                                                                     17170 non-null  float64
 8   Cidade                                                                                                 17170 non-null  object
 9   UF                                                                                                     17170 non-null  object
 10  Data                                                                                                   17170 non-null  object
 11  Rendas de Operações de Crédito (a1)                                                                    13968 non-null  object
 12  Rendas de Operações de Arrendamento Mercantil (a2)                                                     13968 non-null  object
 13  Rendas de Operações com TVM (a3)                                                                       13968 non-null  object
 14  Rendas de Operações com Instrumentos Financeiros Derivativos (a4)                                      13968 non-null  object
 15  Resultado de Operações de Câmbio (a5)                                                                  13968 non-null  object
 16  Rendas de Aplicações Compulsórias (a6)                                                                 13968 non-null  object
 17  Receitas de Intermediação Financeira (a) = (a1) + (a2) + (a3) + (a4) + (a5) + (a6)                     13968 non-null  object
 18  Despesas de Captação (b1)                                                                              13968 non-null  object
 19  Despesas de Obrigações por Empréstimos e Repasses (b2)                                                 13968 non-null  object
 20  Despesas de Operações de Arrendamento Mercantil (b3)                                                   13968 non-null  object
 21  Resultado de Operações de Câmbio (b4)                                                                  13968 non-null  object
 22  Resultado de Provisão para Créditos de Difícil Liquidação (b5)                                         13968 non-null  object
 23  Despesas de Intermediação Financeira (b) = (b1) + (b2) + (b3) + (b4) + (b5)                            13968 non-null  object
 24  Resultado de Intermediação Financeira (c) = (a) + (b)                                                  13968 non-null  object
 25  Rendas de Prestação de Serviços (d1)                                                                   13968 non-null  object
 26  Rendas de Tarifas Bancárias (d2)                                                                       13968 non-null  object
 27  Despesas de Pessoal (d3)                                                                               13968 non-null  object
 28  Despesas Administrativas (d4)                                                                          13968 non-null  object
 29  Despesas Tributárias (d5)                                                                              13968 non-null  object
 30  Resultado de Participações (d6)                                                                        13968 non-null  object
 31  Outras Receitas Operacionais (d7)                                                                      13968 non-null  object
 32  Outras Despesas Operacionais (d8)                                                                      13968 non-null  object
 33  Outras Receitas/Despesas  Operacionais (d) = (d1) + (d2) + (d3) + (d4) + (d5) + (d6) + (d7) + (d8)     13968 non-null  object
 34  Resultado Operacional (e) = (c) + (d)                                                                  13968 non-null  object
 35  Resultado Não Operacional (f)                                                                          13968 non-null  object
 36  Resultado antes da Tributação, Lucro e Participação (g) = (e) + (f)                                    13968 non-null  object
 37  Imposto de Renda e Contribuição Social (h)                                                             13968 non-null  object
 38  Participação nos Lucros (i)                                                                            13968 non-null  object
 39  Lucro Líquido (j) = (g) + (h) + (i)                                                                    13968 non-null  object
 40  Juros Sobre Capital Social de Cooperativas (k)                                                         13968 non-null  object
 41  Coluna_Vazia                                                                                           0 non-null      object
 42  Ativo Total                                                                                            3202 non-null   object
 43  Receita de Juros com Aplicações Interfinanceiras de Liquidez (a1)                                      3202 non-null   object
 44  Ajuste de Variação Cambial de Aplicações Interfinanceiras de Liquidez (a2)                             3202 non-null   object
 45  Ajuste a Valor Justo e Ajuste de Hedge de Valor Justo de Aplicações Interfinanceiras de Liquidez (a3)  3202 non-null   object
 46  Rendas de Aplicações Interfinanceiras de Liquidez (a)                                                  3202 non-null   object
 47  Receita de Juros com TVM (b1)                                                                          3202 non-null   object
 48  Ajuste de Variação Cambial de TVM (b2)                                                                 3202 non-null   object
 49  Ajuste a Valor Justo e Ajuste de Hedge de Valor Justo de TVM (b3)                                      3202 non-null   object
 50  Outros Resultados de TVM (b4)                                                                          3202 non-null   object
 51  Rendas de Títulos e Valores Mobiliários (b)                                                            3202 non-null   object
 52  Receita de Juros com Operações de Crédito (c1)                                                         3202 non-null   object
 53  Ajuste de Variação Cambial de Operações de Crédito (c2)                                                3202 non-null   object
 54  Ajuste a Valor Justo e Ajuste de Hedge de Valor Justo de Operações de Crédito (c3)                     3202 non-null   object
 55  Outros Resultados de Operações de Crédito (c4)                                                         3202 non-null   object
 56  Rendas de Operações de Crédito (c)                                                                     3202 non-null   object
 57  Rendas de Arrendamento Financeiro (d)                                                                  3202 non-null   object
 58  Rendas de Outras Operações com Características de Concessão de Crédito (e)                             3202 non-null   object
 59  Resultado com Perda Esperada de Aplicações Interfinanceiras de Liquidez (f1)                           3202 non-null   object
 60  Resultado com Perda Esperada de TVM (f2)                                                               3202 non-null   object
 61  Resultado com Perda Esperada de Operações de Crédito (f3)                                              3202 non-null   object
 62  Resultado com Perda Esperada de Arrendamento (f4)                                                      3202 non-null   object
 63  Resultado com Perda Esperada de Outras Operações com Características de Concessão de Crédito(f5)       3202 non-null   object
 64  Resultado com Perda Esperada de Outros Ativos Geradores de Renda (f6)                                  3202 non-null   object
 65  Resultado com Perda Esperada (f)                                                                       3202 non-null   object
 66  Despesa de Juros com Captações (g1)                                                                    3202 non-null   object
 67  Ajuste de Variação Cambial de Captações (g2)                                                           3202 non-null   object
 68  Ajuste de Hedge de Valor Justo de Captações (g3)                                                       3202 non-null   object
 69  Outros Resultados de Captações (g4)                                                                    3202 non-null   object
 70  Despesas de Captações (g)                                                                              3202 non-null   object
 71  Despesas de Instrumentos de Dívida Elegíveis a Capital (h)                                             3202 non-null   object
 72  Resultado com Derivativos (i)                                                                          3202 non-null   object
 73  Outros Resultados de Intermediação Financeira (j)                                                      3202 non-null   object
 74  Resultado de Intermediação Financeira (k) = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)  3202 non-null   object
 75  Resultado com Serviços por Transações de Pagamento (l1)                                                3202 non-null   object
 76  Resultados de Perda Esperada com Transações de Pagamento (l2)                                          3202 non-null   object
 77  Outros Resultados com Transações de Pagamento (l3)                                                     3202 non-null   object
 78  Resultado com Transações de Pagamento (l)                                                              3202 non-null   object
 79  Rendas de Tarifas Bancárias (m)                                                                        3202 non-null   object
 80  Outras Rendas de Prestação de Serviços (n)                                                             3202 non-null   object
 81  Despesas de Pessoal (o)                                                                                3202 non-null   object
 82  Despesas Administrativas (p)                                                                           3202 non-null   object
 83  Resultado com Perdas Esperadas de Outras Operações (q)                                                 3202 non-null   object
 84  Despesas de Juros Sobre Capital Próprio de Cooperativas (r)                                            3202 non-null   object
 85  Despesas Tributárias (s)                                                                               3202 non-null   object
 86  Resultado de Participações (t)                                                                         3202 non-null   object
 87  Outras Receitas (u)                                                                                    3202 non-null   object
 88  Outras Despesas (v)                                                                                    3202 non-null   object
 89  Outras Receitas / Despesas (w)= (m) + (n) + (o) +  (p) + (q) + (r) + (s) + (t) + (u) + (v)             3202 non-null   object
 90  Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)                                    3202 non-null   object
 91  Imposto de Renda e Contribuição Social (y)                                                             3202 non-null   object
 92  Participações no Lucro (z)                                                                             3202 non-null   object
 93  Lucro Líquido (aa) = (x) + (y) + (z)                                                                   3202 non-null   object
dtypes: float64(5), object(89)
memory usage: 12.3+ MB

,Instituição,Código,Conglomerado Prudencial,Conglomerado Financeiro,Conglomerado Prudencial_1,TCB,TC,TI,Cidade,UF,...,Despesas de Juros Sobre Capital Próprio de Cooperativas (r),Despesas Tributárias (s),Resultado de Participações (t),Outras Receitas (u),Outras Despesas (v),Outras Receitas / Despesas (w)= (m) + (n) + (o) + (p) + (q) + (r) + (s) + (t) + (u) + (v),Resultado antes da Tributação e Participações (x) = (k) + (l) + (w),Imposto de Renda e Contribuição Social (y),Participações no Lucro (z),Lucro Líquido (aa) = (x) + (y) + (z)
0,BANCO DO BRASIL S.A.,0.0,BB - PRUDENCIAL,49906.0,80329.0,b1,1.0,1.0,BRASILIA,DF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAIXA ECONOMICA FEDERAL,360305.0,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,51626.0,80738.0,b1,1.0,6.0,BRASILIA,DF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ITAÚ UNIBANCO S.A.,60701190.0,ITAU - PRUDENCIAL,10069.0,80099.0,b1,2.0,8.0,SAO PAULO,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BANCO BRADESCO S.A.,60746948.0,BRADESCO - PRUDENCIAL,10045.0,80075.0,b1,2.0,8.0,OSASCO,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BANCO SANTANDER (BRASIL) S.A.,90400888.0,SANTANDER - PRUDENCIAL,30379.0,80185.0,b1,3.0,8.0,SAO PAULO,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17198,BT CORRETORA DE CÂMBIO LTDA.,73622748.0,BT CC - PRUDENCIAL,NaN,81995.0,n2,2.0,21.0,SAO PAULO,SP,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17199,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS TR...,90560434.0,NaN,NaN,NaN,b3S,2.0,9.0,CACHOEIRINHA,RS,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17200,TCB - Tipo de Consolidado Bancário,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17201,TC - Tipo de Controle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17202,TI - Tipo de Instituição,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
df_dre = df_dre_total.copy()

# Equalização das colunas, pois ao longo dos anos foram feitas mudanças nos nomes.
# Correção da Lógica: New.fillna(Old)

df_dre['Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)'] = \
    df_dre['Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)'].fillna(df_dre['Resultado antes da Tributação, Lucro e Participação (g) = (e) + (f)'])

df_dre['Lucro Líquido (aa) = (x) + (y) + (z)'] = \
    df_dre['Lucro Líquido (aa) = (x) + (y) + (z)'].fillna(df_dre['Lucro Líquido (j) = (g) + (h) + (i)'])

df_dre['Outras Receitas / Despesas (w)= (m) + (n) + (o) +  (p) + (q) + (r) + (s) + (t) + (u) + (v)'] = \
    df_dre['Outras Receitas / Despesas (w)= (m) + (n) + (o) +  (p) + (q) + (r) + (s) + (t) + (u) + (v)'].fillna(df_dre['Outras Receitas/Despesas  Operacionais (d) = (d1) + (d2) + (d3) + (d4) + (d5) + (d6) + (d7) + (d8)'])

df_dre['Participações no Lucro (z)'] = \
    df_dre['Participações no Lucro (z)'].fillna(df_dre['Participação nos Lucros (i)'])

df_dre['Imposto de Renda e Contribuição Social (y)'] = \
    df_dre['Imposto de Renda e Contribuição Social (y)'].fillna(df_dre['Imposto de Renda e Contribuição Social (h)'])

df_dre['Resultado com Transações de Pagamento (l)'] = \
    df_dre['Resultado com Transações de Pagamento (l)'].fillna('0')

df_dre['Resultado de Intermediação Financeira (k) = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)'] = \
    df_dre['Resultado de Intermediação Financeira (k) = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)'].fillna(df_dre['Resultado de Intermediação Financeira (c) = (a) + (b)'])

df_dre['Rendas de Tarifas Bancárias (m)'] = \
    df_dre['Rendas de Tarifas Bancárias (m)'].fillna(df_dre['Rendas de Prestação de Serviços (d1)'])

df_dre['Outras Rendas de Prestação de Serviços (n)'] = \
    df_dre['Outras Rendas de Prestação de Serviços (n)'].fillna(df_dre['Rendas de Tarifas Bancárias (d2)'])

df_dre['Despesas Administrativas (p)'] = \
    df_dre['Despesas Administrativas (p)'].fillna(df_dre['Despesas Administrativas (d4)'])

df_dre['Despesas de Pessoal (o)'] = \
    df_dre['Despesas de Pessoal (o)'].fillna(df_dre['Despesas de Pessoal (d3)'])

df_dre['Despesas Tributárias (s)'] = \
    df_dre['Despesas Tributárias (s)'].fillna(df_dre['Despesas Tributárias (d5)'])

df_dre['Resultado de Participações (t)'] = \
    df_dre['Resultado de Participações (t)'].fillna(df_dre['Resultado de Participações (d6)'])

df_dre['Outras Receitas (u)'] = \
    df_dre['Outras Receitas (u)'].fillna(df_dre['Outras Receitas Operacionais (d7)'])

df_dre['Outras Despesas (v)'] = \
    df_dre['Outras Despesas (v)'].fillna(df_dre['Outras Despesas Operacionais (d8)'])

df_dre['Despesa de Juros com Captações (g1)'] = \
    df_dre['Despesa de Juros com Captações (g1)'].fillna(df_dre['Despesas de Captação (b1)'])

df_dre['Rendas de Operações de Crédito (c)'] = \
    df_dre['Rendas de Operações de Crédito (c)'].fillna(df_dre['Rendas de Operações de Crédito (a1)'])

df_dre['Rendas de Títulos e Valores Mobiliários (b)'] = \
    df_dre['Rendas de Títulos e Valores Mobiliários (b)'].fillna(df_dre['Rendas de Operações com TVM (a3)'])

df_dre['Resultado com Derivativos (i)'] = \
    df_dre['Resultado com Derivativos (i)'].fillna(df_dre['Rendas de Operações com Instrumentos Financeiros Derivativos (a4)'])

df_dre['Resultado com Perda Esperada (f)'] = \
    df_dre['Resultado com Perda Esperada (f)'].fillna(df_dre['Resultado de Provisão para Créditos de Difícil Liquidação (b5)'])

# Lista Completa de Colunas Velhas para Excluir
colunas_velhas_para_excluir = [
    'Conglomerado Financeiro',
    'Conglomerado Prudencial_1',
    'Ativo Total',
    'Coluna_Vazia',
    'Resultado antes da Tributação, Lucro e Participação (g) = (e) + (f)',
    'Lucro Líquido (j) = (g) + (h) + (i)',
    'Outras Receitas/Despesas  Operacionais (d) = (d1) + (d2) + (d3) + (d4) + (d5) + (d6) + (d7) + (d8)',
    'Imposto de Renda e Contribuição Social (h)',
    'Participação nos Lucros (i)',
    'Juros Sobre Capital Social de Cooperativas (k)',
    'Resultado Operacional (e) = (c) + (d)',
    'Resultado Não Operacional (f)',
    'Receitas de Intermediação Financeira (a) = (a1) + (a2) + (a3) + (a4) + (a5) + (a6)',
    'Resultado de Intermediação Financeira (c) = (a) + (b)',
    'Despesas de Intermediação Financeira (b) = (b1) + (b2) + (b3) + (b4) + (b5)',
    'Despesas de Captações (g)',
    'Despesas de Captação (b1)',
    'Rendas de Prestação de Serviços (d1)',
    'Rendas de Tarifas Bancárias (d2)',
    'Despesas Administrativas (d4)',
    'Despesas de Pessoal (d3)',
    'Despesas Tributárias (d5)',
    'Resultado de Participações (d6)',
    'Outras Receitas Operacionais (d7)',
    'Outras Despesas Operacionais (d8)',
    'Rendas de Operações de Crédito (a1)',
    'Rendas de Operações com Instrumentos Financeiros Derivativos (a4)',
    'Resultado de Provisão para Créditos de Difícil Liquidação (b5)'
]

df_dre = df_dre.dropna(subset='Cidade')
df_dre = df_dre.drop(columns=colunas_velhas_para_excluir)

contagem_alvo = df_dre['Instituição'].count()
condicao_completa = df_dre.count() == contagem_alvo
condicao_excecao = df_dre.columns == 'Conglomerado Prudencial'

df_dre = df_dre.loc[:, condicao_completa | condicao_excecao] # Exclui colunas que não tem o numero que sustente um histórico completo

# Salvar o dataframe bruto na pasta 'RAW'.
df_dre.to_parquet(os.path.join(caminho_raw, "dre_raw.parquet"), index=False)

df_dre.info()
df_dre

<class 'pandas.core.frame.DataFrame'>
Index: 17170 entries, 0 to 17199
Data columns (total 29 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   Instituição                                                                                            17170 non-null  object
 1   Código                                                                                                 17170 non-null  float64
 2   Conglomerado Prudencial                                                                                8373 non-null   object
 3   TCB                                                                                                    17170 non-null  object
 4   TC                                                                                                     17170 non-null  float64
 5   TI                                                                                                     17170 non-null  float64
 6   Cidade                                                                                                 17170 non-null  object
 7   UF                                                                                                     17170 non-null  object
 8   Data                                                                                                   17170 non-null  object
 9   Rendas de Títulos e Valores Mobiliários (b)                                                            17170 non-null  object
 10  Rendas de Operações de Crédito (c)                                                                     17170 non-null  object
 11  Resultado com Perda Esperada (f)                                                                       17170 non-null  object
 12  Despesa de Juros com Captações (g1)                                                                    17170 non-null  object
 13  Resultado com Derivativos (i)                                                                          17170 non-null  object
 14  Resultado de Intermediação Financeira (k) = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)  17170 non-null  object
 15  Resultado com Transações de Pagamento (l)                                                              17170 non-null  object
 16  Rendas de Tarifas Bancárias (m)                                                                        17170 non-null  object
 17  Outras Rendas de Prestação de Serviços (n)                                                             17170 non-null  object
 18  Despesas de Pessoal (o)                                                                                17170 non-null  object
 19  Despesas Administrativas (p)                                                                           17170 non-null  object
 20  Despesas Tributárias (s)                                                                               17170 non-null  object
 21  Resultado de Participações (t)                                                                         17170 non-null  object
 22  Outras Receitas (u)                                                                                    17170 non-null  object
 23  Outras Despesas (v)                                                                                    17170 non-null  object
 24  Outras Receitas / Despesas (w)= (m) + (n) + (o) +  (p) + (q) + (r) + (s) + (t) + (u) + (v)             17170 non-null  object
 25  Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)                                    17170 non-null  object
 26  Imposto de Renda e Contribuição Social (y)                                                             17170 non-null  object
 27  Participações no Lucro (z)                                                                             17170 non-null  object
 28  Lucro Líquido (aa) = (x) + (y) + (z)                                                                   17170 non-null  object
dtypes: float64(3), object(26)
memory usage: 3.9+ MB

,Instituição,Código,Conglomerado Prudencial,TCB,TC,TI,Cidade,UF,Data,Rendas de Títulos e Valores Mobiliários (b),...,Despesas Administrativas (p),Despesas Tributárias (s),Resultado de Participações (t),Outras Receitas (u),Outras Despesas (v),Outras Receitas / Despesas (w)= (m) + (n) + (o) + (p) + (q) + (r) + (s) + (t) + (u) + (v),Resultado antes da Tributação e Participações (x) = (k) + (l) + (w),Imposto de Renda e Contribuição Social (y),Participações no Lucro (z),Lucro Líquido (aa) = (x) + (y) + (z)
0,BANCO DO BRASIL S.A.,0.0,BB - PRUDENCIAL,b1,1.0,1.0,BRASILIA,DF,12/2022,58.596.285,...,-5.237.470,-2.451.338,8.284.131,10.796.191,-7.750.692,3.317.134,21.753.526,-2.982.566,-2.132.589,16.638.371
1,CAIXA ECONOMICA FEDERAL,360305.0,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1.0,6.0,BRASILIA,DF,12/2022,24.831.667,...,-5.973.955,-1.999.036,2.041.360,6.311.604,-11.957.151,-13.944.940,5.582.178,971.396,-1.060.139,5.493.435
2,ITAÚ UNIBANCO S.A.,60701190.0,ITAU - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,12/2022,43.986.868,...,-8.321.352,-1.936.088,8.502.395,8.463.879,-6.389.630,2.758.344,18.299.359,1.334.900,-3.690.333,15.943.927
3,BANCO BRADESCO S.A.,60746948.0,BRADESCO - PRUDENCIAL,b1,2.0,8.0,OSASCO,SP,12/2022,35.028.544,...,-9.713.000,-2.397.203,7.669.313,6.842.800,-7.288.312,-3.427.060,2.897.870,3.749.785,0,6.647.656
4,BANCO SANTANDER (BRASIL) S.A.,90400888.0,SANTANDER - PRUDENCIAL,b1,3.0,8.0,SAO PAULO,SP,12/2022,16.816.762,...,-6.080.297,-1.577.849,4.935.164,13.118.048,-13.289.969,1.739.955,2.602.071,2.970.185,-990.117,4.582.139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17195,CREDI-SHOP - SOCIEDADE DE CRÉDITO DIRETO S.A.,54733010.0,CREDI SHOP S.A. - PRUDENCIAL,n1,2.0,43.0,TERESINA,PI,06/2025,NI,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17196,PERSONAL SOCIEDADE DE CRÉDITO DIRETO S.A.,57905133.0,PERSONAL SCD - PRUDENCIAL,n1,2.0,43.0,FLORIANOPOLIS,SC,06/2025,NI,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17197,BANCO PINE S.A.,62144175.0,PINE - PRUDENCIAL,b1,2.0,8.0,SAO PAULO,SP,06/2025,NI,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17198,BT CORRETORA DE CÂMBIO LTDA.,73622748.0,BT CC - PRUDENCIAL,n2,2.0,21.0,SAO PAULO,SP,06/2025,NI,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI
17199,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS TR...,90560434.0,NaN,b3S,2.0,9.0,CACHOEIRINHA,RS,06/2025,NI,...,NI,NI,NI,NI,NI,NI,NI,NI,NI,NI